### PR TITLE
[KED-2354] Make kedro-docker work with kedro 0.17.0

### PR DESCRIPTION
**Pull request by MerelTheisenQB**
## Motivation and Context
The `kedro docker run` doesn't work with Kedro 0.17.0 and throws `TypeError: docker_run() got an unexpected keyword argument 'verbose'`

It turns out this command and several others were missing kwargs as argument. 

e2e tests were failing with 0.17.0 as well, so I changed the test setup to use the pandas-iris starter.

## How has this been tested?
Tested locally on a new Kedro project created with Kedro 0.17.0

## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [X] Assigned myself to the PR
- [ ] Added tests to cover my changes
- [ ] Added new entries to the `RELEASE.md` file

## Notice

- [X] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

File: .circleci/config.yml [hunk 1]
```diff
@@ -48,7 +48,7 @@ commands:
           command: |
             python -V
             pip -V
-            kedro -V
+#            kedro -V
```
Comment (MerelTheisenQB) [inline .circleci/config.yml:51]: Temporarily disabled this step, because it fails by assuming that every directory with a `pyproject.toml` file is a kedro project. https://quantumblack.slack.com/archives/GDQM0670Q/p1609848840013500

File: kedro_docker/plugin.py [hunk 2]
```diff
@@ -233,7 +233,7 @@ def _mount_info() -> Dict[str, Union[str, Tuple]]:
 @forward_command(docker_group, "run")
 @_make_image_option(callback=_image_callback)
 @_make_docker_args_option()
-def docker_run(image, docker_args, args):
+def docker_run(image, docker_args, args, **kwargs):  # pylint: disable=unused-argument
```
Comment (lorenabalan) [inline kedro_docker/plugin.py:236]: Can we make a note somewhere that `**kwargs` is there to make the global `verbose` work and pass it through?

**Review by lorenabalan — APPROVED** [review]
Nice one! ✨

File: kedro_docker/plugin.py (hunk 2 above)
Comment (lorenabalan) [reply kedro_docker/plugin.py:236]: As in a comment in the code. I think we might forget otherwise.

**Review by limdauto — APPROVED** [review]
Awesome
